apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: node
  name: node
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: node
    spec:
      containers:
      - env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              key: NODE_ENV
              name: node-docker-env-app-development-env
        image: danwahlin/node-codewithdan
        imagePullPolicy: IfNotPresent
        name: node-codewithdan
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /var/www/codewithdan
          name: node-claim0
        workingDir: /var/www/codewithdan
      restartPolicy: Always
      volumes:
      - name: node-claim0
        persistentVolumeClaim:
          claimName: node-claim0
status: {}
